### ISSUE TITLE
Incorrct Solution LastStoneWeight_1046

### ISSUE THREAD

**Issue by bluecloudes** [nanofaroque/Life-coding#1]
https://github.com/nanofaroque/Life-coding/blob/master/src/leetcode/contests/contest_137/LastStoneWeight_1046.java

Input
[31,26,33,21,40]
Output
9
Expected
5

**Comment by nanofaroque** [comment]
Here is the original problem: https://leetcode.com/problems/last-stone-weight/
My solution has passed all the test cases. I have an article about this problem as well. You can check it out here: https://medium.com/me/stats/post/dbc948aab8a
