### ISSUE TITLE
issue in Life-coding/src/leetcode/contests/contest_159/CheckStraightLine.java

### ISSUE THREAD

**Issue by 177shivam** [nanofaroque/Life-coding#5]
Your CheckStraightLine.java gives wrong answer on testcase [[0,0],[0,5],[5,0],[1337,0],[0,1337]].
To solve this issue you have to sort coordinates and then apply your algorithm.

**Comment by nanofaroque** [comment]
Your test case is wrong. A line with [0,5],[5,0] will never pass through origin [0,0]

**Comment by 177shivam** [comment]
So this is not straight line then it should give ans **false it's not a straight line** but your code gives output **yes it is straight line**.
